--USUARIO MIGRACION
SET IDENTITY_INSERT [dbo].[TBL_USUARIOS] ON 
INSERT [TBL_USUARIOS] ([ID_USUARIO],[LOGIN], [NOMBRE],[ID_USUARIO_SGAA], [DIR_CORREO], [ACTIVO]) VALUES (1, N'MIGRACION', N'MIGRACION',0, N'MIGRACION', 1);
SET IDENTITY_INSERT [dbo].[TBL_USUARIOS] OFF


--Tipos de acceso para las funcionalidades
SET IDENTITY_INSERT [dbo].[TBL_TIPOS_ACCESO] ON 
INSERT INTO [dbo].[TBL_TIPOS_ACCESO](ID_TIPO_ACCESO, DESCRIPCION, ACTIVO, ID_USUARIO_ALTA, FECHA_ALTA)
VALUES(1,'Acceso Total', 1, 1, GETDATE()), (2,'Consulta', 1, 1, GETDATE())
SET IDENTITY_INSERT [dbo].[TBL_TIPOS_ACCESO] OFF