//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioIntegradorMVC_1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjercicioIntegradorMVC_1.Resources.ResourceGlobal", typeof(ResourceGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Cambios.
        /// </summary>
        public static string BotonAplicarCambios {
            get {
                return ResourceManager.GetString("BotonAplicarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string BotonConfirmar {
            get {
                return ResourceManager.GetString("BotonConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar al menu principal.
        /// </summary>
        public static string BotonRegreso {
            get {
                return ResourceManager.GetString("BotonRegreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        public static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE.
        /// </summary>
        public static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe indicar un {0} de la lista..
        /// </summary>
        public static string MensajeErrorList {
            get {
                return ResourceManager.GetString("MensajeErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo TipoDoc debe ser DNI ({0}), LE (2) o LC ({1})..
        /// </summary>
        public static string MensajeErrorRange {
            get {
                return ResourceManager.GetString("MensajeErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio..
        /// </summary>
        public static string MensajeErrorRequired {
            get {
                return ResourceManager.GetString("MensajeErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no debe superar los {1} caracteres..
        /// </summary>
        public static string MensajeErrorStringLength {
            get {
                return ResourceManager.GetString("MensajeErrorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener {1} numeros..
        /// </summary>
        public static string MensajeErrorStringLengthNumeroDocumento {
            get {
                return ResourceManager.GetString("MensajeErrorStringLengthNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Id.
        /// </summary>
        public static string MensajeListaDespegableId {
            get {
                return ResourceManager.GetString("MensajeListaDespegableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un tipo de documento.
        /// </summary>
        public static string MensajeListaDespegableTipoDeDocumento {
            get {
                return ResourceManager.GetString("MensajeListaDespegableTipoDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Documento.
        /// </summary>
        public static string NumeroDeDocumento {
            get {
                return ResourceManager.GetString("NumeroDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicio Integrador MVC #1.
        /// </summary>
        public static string PieDePagina {
            get {
                return ResourceManager.GetString("PieDePagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string TipoDeDocumento {
            get {
                return ResourceManager.GetString("TipoDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Persona.
        /// </summary>
        public static string TituloAgregarPersona {
            get {
                return ResourceManager.GetString("TituloAgregarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La persona se agrego / modifico a la base de datos correctamente.
        /// </summary>
        public static string TituloExito {
            get {
                return ResourceManager.GetString("TituloExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas - MVC.
        /// </summary>
        public static string TituloIndex {
            get {
                return ResourceManager.GetString("TituloIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Personas.
        /// </summary>
        public static string TituloListarPersonas {
            get {
                return ResourceManager.GetString("TituloListarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Persona.
        /// </summary>
        public static string TituloModificarPersona {
            get {
                return ResourceManager.GetString("TituloModificarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicio Integrador MVC #1.
        /// </summary>
        public static string TituloVentana {
            get {
                return ResourceManager.GetString("TituloVentana", resourceCulture);
            }
        }
    }
}
