//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARQ.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARQ.Recursos.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        public static string Activa {
            get {
                return ResourceManager.GetString("Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Cliente.
        /// </summary>
        public static string AgregarCliente {
            get {
                return ResourceManager.GetString("AgregarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Funcionalidad.
        /// </summary>
        public static string AgregarFuncionalidad {
            get {
                return ResourceManager.GetString("AgregarFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Material.
        /// </summary>
        public static string AgregarMaterial {
            get {
                return ResourceManager.GetString("AgregarMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Rol y Tipo Acceso.
        /// </summary>
        public static string AgregarRolYTipoAcceso {
            get {
                return ResourceManager.GetString("AgregarRolYTipoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Filtros.
        /// </summary>
        public static string AplicarFiltros {
            get {
                return ResourceManager.GetString("AplicarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arquitectura Codes.
        /// </summary>
        public static string ARQTitle {
            get {
                return ResourceManager.GetString("ARQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string ClickIngresar {
            get {
                return ResourceManager.GetString("ClickIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar password.
        /// </summary>
        public static string ConfirmarPassword {
            get {
                return ResourceManager.GetString("ConfirmarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Roles Acceso.
        /// </summary>
        public static string EditarRolesAcceso {
            get {
                return ResourceManager.GetString("EditarRolesAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado. Por favor, contacte con el area de sistemas..
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Excel.
        /// </summary>
        public static string ExportarExcel {
            get {
                return ResourceManager.GetString("ExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        public static string Funcionalidad {
            get {
                return ResourceManager.GetString("Funcionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidades.
        /// </summary>
        public static string Funcionalidades {
            get {
                return ResourceManager.GetString("Funcionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactiva.
        /// </summary>
        public static string Inactiva {
            get {
                return ResourceManager.GetString("Inactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivar.
        /// </summary>
        public static string Inactivar {
            get {
                return ResourceManager.GetString("Inactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Filtros.
        /// </summary>
        public static string LimpiarFiltros {
            get {
                return ResourceManager.GetString("LimpiarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado.
        /// </summary>
        public static string Listado {
            get {
                return ResourceManager.GetString("Listado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materiales.
        /// </summary>
        public static string Materiales {
            get {
                return ResourceManager.GetString("Materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea inactivar el cliente?.
        /// </summary>
        public static string MensajeClienteInactivar {
            get {
                return ResourceManager.GetString("MensajeClienteInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o password son incorrectos..
        /// </summary>
        public static string MensajeCredencialesInvalidas {
            get {
                return ResourceManager.GetString("MensajeCredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente.
        /// </summary>
        public static string MensajeDatosGuardadosOk {
            get {
                return ResourceManager.GetString("MensajeDatosGuardadosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la reliación con el rol seleccionado?.
        /// </summary>
        public static string MensajeEliminarRol {
            get {
                return ResourceManager.GetString("MensajeEliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea inactivar:.
        /// </summary>
        public static string MensajeFuncionalidadInactivar {
            get {
                return ResourceManager.GetString("MensajeFuncionalidadInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea inactivar el material?.
        /// </summary>
        public static string MensajeMaterialInactivar {
            get {
                return ResourceManager.GetString("MensajeMaterialInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No autorizado.
        /// </summary>
        public static string MensajeNoAutorizado {
            get {
                return ResourceManager.GetString("MensajeNoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arquitectura Codes.
        /// </summary>
        public static string MenuARQ {
            get {
                return ResourceManager.GetString("MenuARQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplicador Toneladas.
        /// </summary>
        public static string MultiplicadorToneladas {
            get {
                return ResourceManager.GetString("MultiplicadorToneladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva.
        /// </summary>
        public static string Nueva {
            get {
                return ResourceManager.GetString("Nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arquitectura Codes.
        /// </summary>
        public static string PieDeAplicacion {
            get {
                return ResourceManager.GetString("PieDeAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor revise.
        /// </summary>
        public static string PorFavorRevise {
            get {
                return ResourceManager.GetString("PorFavorRevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede inactivar porque se encuentra relacionado/a con.
        /// </summary>
        public static string RelatedEntityExceptionMessage {
            get {
                return ResourceManager.GetString("RelatedEntityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rodillo.
        /// </summary>
        public static string Rodillo {
            get {
                return ResourceManager.GetString("Rodillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Rol.
        /// </summary>
        public static string SeleccioneRol {
            get {
                return ResourceManager.GetString("SeleccioneRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tipo Acceso.
        /// </summary>
        public static string SeleccioneTipoAcceso {
            get {
                return ResourceManager.GetString("SeleccioneTipoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Acceso.
        /// </summary>
        public static string TipoAcceso {
            get {
                return ResourceManager.GetString("TipoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas.
        /// </summary>
        public static string Todas {
            get {
                return ResourceManager.GetString("Todas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha olvidado ingresar su Contraseña.
        /// </summary>
        public static string ValidacionCampoPasswordRequerido {
            get {
                return ResourceManager.GetString("ValidacionCampoPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha olvidado ingresar su Usuario.
        /// </summary>
        public static string ValidacionCampoUsuarioRequerido {
            get {
                return ResourceManager.GetString("ValidacionCampoUsuarioRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string ValidacionConfirmarClave {
            get {
                return ResourceManager.GetString("ValidacionConfirmarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al inicio.
        /// </summary>
        public static string VolverAlInicio {
            get {
                return ResourceManager.GetString("VolverAlInicio", resourceCulture);
            }
        }
    }
}
