-- CREATE DATABASE DBPracticaCODES;

USE DBPracticaCODES;

CREATE TABLE Persona (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50),
    Apellido VARCHAR(50),
    Edad INT,
	DNI VARCHAR(8),
	Email VARCHAR(50)
);

SELECT * FROM Persona
SELECT * FROM Persona WHERE Edad LIKE ' ';