//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjercicioIntegradorMVC_2.Recursos.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Accion_Cancelar {
            get {
                return ResourceManager.GetString("Accion_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Accion_Eliminar {
            get {
                return ResourceManager.GetString("Accion_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Accion_Regresar {
            get {
                return ResourceManager.GetString("Accion_Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Boton_Aceptar {
            get {
                return ResourceManager.GetString("Boton_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Proveedor.
        /// </summary>
        public static string Boton_Agregar_Proveedor {
            get {
                return ResourceManager.GetString("Boton_Agregar_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Boton_Buscar {
            get {
                return ResourceManager.GetString("Boton_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Label_Filtro_Proveedor_Localidad_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Localidad_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Proveedor.
        /// </summary>
        public static string Label_Filtro_Proveedor_Nombre_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Nombre_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Label_Filtro_Proveedor_Provincia_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Provincia_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio..
        /// </summary>
        public static string Mensaje_Error_Required {
            get {
                return ResourceManager.GetString("Mensaje_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una {0} de la lista..
        /// </summary>
        public static string Mensaje_Error_Select_Required {
            get {
                return ResourceManager.GetString("Mensaje_Error_Select_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  El campo {1} debe ser menor que {0} caracteres..
        /// </summary>
        public static string Mensaje_Error_String_Length {
            get {
                return ResourceManager.GetString("Mensaje_Error_String_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        public static string Proveedor_Domicilio_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Domicilio_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Proveedor_Localidad_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Localidad_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Proveedor_Nombre_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Nombre_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Proveedor_Provincia_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Provincia_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una localidad.
        /// </summary>
        public static string Select_Localidad_Mensaje {
            get {
                return ResourceManager.GetString("Select_Localidad_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una provincia.
        /// </summary>
        public static string Select_Provincia_Mensaje {
            get {
                return ResourceManager.GetString("Select_Provincia_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una localidad.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Localidad {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un nombre.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Nombre {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una provincia.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Provincia {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Proveedor.
        /// </summary>
        public static string Titulo_DetalleProveedor {
            get {
                return ResourceManager.GetString("Titulo_DetalleProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Proveedor.
        /// </summary>
        public static string Titulo_Edit {
            get {
                return ResourceManager.GetString("Titulo_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABM - Proveedores.
        /// </summary>
        public static string Titulo_Indice {
            get {
                return ResourceManager.GetString("Titulo_Indice", resourceCulture);
            }
        }
    }
}
