//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioIntegradorMVC_1_VM.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGlobal() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjercicioIntegradorMVC_1_VM.Resources.ResourceGlobal", typeof(ResourceGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Cambios.
        /// </summary>
        public static string BotonAplicarCambios {
            get {
                return ResourceManager.GetString("BotonAplicarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string BotonConfirmar {
            get {
                return ResourceManager.GetString("BotonConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar al menu principal.
        /// </summary>
        public static string BotonRegreso {
            get {
                return ResourceManager.GetString("BotonRegreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LC.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LE.
        /// </summary>
        public static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe indicar un {0} de la lista..
        /// </summary>
        public static string MensajeErrorList {
            get {
                return ResourceManager.GetString("MensajeErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo TipoDoc debe ser DNI ({0}), LE (2) o LC ({1})..
        /// </summary>
        public static string MensajeErrorRange {
            get {
                return ResourceManager.GetString("MensajeErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio..
        /// </summary>
        public static string MensajeErrorRequired {
            get {
                return ResourceManager.GetString("MensajeErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no debe superar los {1} caracteres..
        /// </summary>
        public static string MensajeErrorStringLength {
            get {
                return ResourceManager.GetString("MensajeErrorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener {1} numeros..
        /// </summary>
        public static string MensajeErrorStringLengthNumeroDocumento {
            get {
                return ResourceManager.GetString("MensajeErrorStringLengthNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Id.
        /// </summary>
        public static string MensajeListaDespegableId {
            get {
                return ResourceManager.GetString("MensajeListaDespegableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de documento.
        /// </summary>
        public static string MensajeListaDespegableTipoDeDocumento {
            get {
                return ResourceManager.GetString("MensajeListaDespegableTipoDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Documento.
        /// </summary>
        public static string NumeroDeDocumento {
            get {
                return ResourceManager.GetString("NumeroDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio Integrador MVC #1.
        /// </summary>
        public static string PieDePagina {
            get {
                return ResourceManager.GetString("PieDePagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento.
        /// </summary>
        public static string TipoDeDocumento {
            get {
                return ResourceManager.GetString("TipoDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Persona.
        /// </summary>
        public static string TituloAgregarPersona {
            get {
                return ResourceManager.GetString("TituloAgregarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona se agrego / modifico a la base de datos correctamente.
        /// </summary>
        public static string TituloExito {
            get {
                return ResourceManager.GetString("TituloExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas - MVC.
        /// </summary>
        public static string TituloIndex {
            get {
                return ResourceManager.GetString("TituloIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listar Personas.
        /// </summary>
        public static string TituloListarPersonas {
            get {
                return ResourceManager.GetString("TituloListarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Persona.
        /// </summary>
        public static string TituloModificarPersona {
            get {
                return ResourceManager.GetString("TituloModificarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio Integrador MVC #1.
        /// </summary>
        public static string TituloVentana {
            get {
                return ResourceManager.GetString("TituloVentana", resourceCulture);
            }
        }
    }
}
