//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjercicioIntegradorMVC_2_VM.Recursos.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Accion_Cancelar {
            get {
                return ResourceManager.GetString("Accion_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Accion_Eliminar {
            get {
                return ResourceManager.GetString("Accion_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Accion_Regresar {
            get {
                return ResourceManager.GetString("Accion_Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Boton_Aceptar {
            get {
                return ResourceManager.GetString("Boton_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Proveedor.
        /// </summary>
        public static string Boton_Agregar_Proveedor {
            get {
                return ResourceManager.GetString("Boton_Agregar_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Boton_Buscar {
            get {
                return ResourceManager.GetString("Boton_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        public static string Label_Filtro_Proveedor_Localidad_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Localidad_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Proveedor.
        /// </summary>
        public static string Label_Filtro_Proveedor_Nombre_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Nombre_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Label_Filtro_Proveedor_Provincia_Texto {
            get {
                return ResourceManager.GetString("Label_Filtro_Proveedor_Provincia_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio..
        /// </summary>
        public static string Mensaje_Error_Required {
            get {
                return ResourceManager.GetString("Mensaje_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una {0} de la lista..
        /// </summary>
        public static string Mensaje_Error_Select_Required {
            get {
                return ResourceManager.GetString("Mensaje_Error_Select_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {1} debe ser menor que {0} caracteres..
        /// </summary>
        public static string Mensaje_Error_String_Length {
            get {
                return ResourceManager.GetString("Mensaje_Error_String_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        public static string Proveedor_Domicilio_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Domicilio_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        public static string Proveedor_Localidad_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Localidad_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Proveedor_Nombre_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Nombre_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Proveedor_Provincia_Texto_Mostrar {
            get {
                return ResourceManager.GetString("Proveedor_Provincia_Texto_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una localidad.
        /// </summary>
        public static string Select_Localidad_Mensaje {
            get {
                return ResourceManager.GetString("Select_Localidad_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una provincia.
        /// </summary>
        public static string Select_Provincia_Mensaje {
            get {
                return ResourceManager.GetString("Select_Provincia_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una localidad.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Localidad {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Nombre {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una provincia.
        /// </summary>
        public static string TextBox_Placeholder_Filtro_Proveedor_Provincia {
            get {
                return ResourceManager.GetString("TextBox_Placeholder_Filtro_Proveedor_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del Proveedor.
        /// </summary>
        public static string Titulo_DetalleProveedor {
            get {
                return ResourceManager.GetString("Titulo_DetalleProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Proveedor.
        /// </summary>
        public static string Titulo_Edit {
            get {
                return ResourceManager.GetString("Titulo_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM - Proveedores.
        /// </summary>
        public static string Titulo_Indice {
            get {
                return ResourceManager.GetString("Titulo_Indice", resourceCulture);
            }
        }
    }
}
